apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cathode-screening

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - backend-deployment.yaml
  - celery-deployment.yaml
  - frontend-deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.3.0"
