apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cathode-artifacts
  namespace: cathode-screening
  labels:
    app.kubernetes.io/name: cathode-screening
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cathode-data
  namespace: cathode-screening
  labels:
    app.kubernetes.io/name: cathode-screening
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
