steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/cathode-screening/chgnet-training:latest', '-f', 'Dockerfile.training', '.' ]
images:
- 'gcr.io/cathode-screening/chgnet-training:latest'
options:
  logging: CLOUD_LOGGING_ONLY
