apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cathode-backend-pdb
  namespace: cathode-screening
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cathode-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cathode-frontend-pdb
  namespace: cathode-screening
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cathode-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: cathode-screening
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
