"""
Phase 7D: Download WBM (Wolverton Battery Materials) Dataset.

WBM contains 257,487 structures generated by single-element substitution
on Materials Project structures. Uses same DFT settings as MP (PBE+U).

Source: Matbench Discovery / Figshare

Usage:
    python scripts/31_download_wbm.py

Output:
    data/external/wbm/wbm_li_cathodes.parquet
    data/external/wbm/structures.pkl
"""

import json
import os
import pickle
import time
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
import requests
from tqdm import tqdm

try:
    from pymatgen.core import Structure
    HAS_PYMATGEN = True
except ImportError:
    HAS_PYMATGEN = False

# Output directory
OUTPUT_DIR = Path("data/external/wbm")

# WBM dataset URLs (Figshare - correct URL from user)
# https://figshare.com/articles/dataset/WBM_Dataset/23713842?file=41619375
WBM_URLS = {
    "summary": "https://figshare.com/ndownloader/files/41619375",  # WBM_Dataset
}

# Transition metals for cathode filtering
TRANSITION_METALS = {"Fe", "Co", "Ni", "Mn", "V", "Cr", "Ti", "Cu", "Zn", "Mo", "W"}


def setup_directories() -> None:
    """Create output directories."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def download_file(url: str, output_path: Path, chunk_size: int = 8192) -> bool:
    """Download a file with progress bar."""
    try:
        response = requests.get(url, stream=True, timeout=300)
        response.raise_for_status()
        
        total_size = int(response.headers.get("content-length", 0))
        
        with open(output_path, "wb") as f:
            with tqdm(total=total_size, unit="B", unit_scale=True, desc=output_path.name) as pbar:
                for chunk in response.iter_content(chunk_size=chunk_size):
                    if chunk:
                        f.write(chunk)
                        pbar.update(len(chunk))
        
        return True
    except Exception as e:
        print(f"Download error: {e}")
        return False


def download_wbm_summary() -> Optional[pd.DataFrame]:
    """Download WBM summary using matbench_discovery package or direct URL."""
    summary_path = OUTPUT_DIR / "wbm_summary.csv.gz"
    
    # Try using matbench_discovery package first
    try:
        from matbench_discovery.data import load_wbm
        print("Loading WBM via matbench_discovery package...")
        df = load_wbm()
        print(f"  Total WBM materials: {len(df)}")
        return df
    except ImportError:
        print("matbench_discovery not installed, trying direct download...")
    except Exception as e:
        print(f"matbench_discovery failed: {e}, trying direct download...")
    
    # Fallback: direct download with browser-like headers
    if not summary_path.exists():
        print("Downloading WBM summary...")
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        }
        try:
            response = requests.get(WBM_URLS["summary"], headers=headers, timeout=300, stream=True)
            response.raise_for_status()
            
            with open(summary_path, "wb") as f:
                for chunk in response.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)
        except Exception as e:
            print(f"Download error: {e}")
            print("\nTo fix: pip install matbench_discovery")
            return None
    
    print("Loading WBM summary...")
    import gzip
    df = pd.read_csv(summary_path, compression='gzip')
    print(f"  Total WBM materials: {len(df)}")
    
    return df


def filter_li_cathodes(df: pd.DataFrame) -> pd.DataFrame:
    """
    Filter WBM dataset for Li-containing oxide cathode materials.
    
    Criteria:
    - Contains Li
    - Contains O
    - Contains at least one transition metal
    - E_hull < 0.5 eV/atom (reasonable stability)
    """
    print("Filtering for Li-cathode materials...")
    
    # Check for required columns
    required_cols = ["formula", "e_above_hull"]
    for col in required_cols:
        if col not in df.columns:
            print(f"Warning: Missing column {col}")
            return pd.DataFrame()
    
    def is_li_cathode(formula: str) -> bool:
        """Check if formula represents a Li-cathode material."""
        if not isinstance(formula, str):
            return False
        
        # Must contain Li and O
        if "Li" not in formula or "O" not in formula:
            return False
        
        # Must contain at least one transition metal
        has_tm = any(tm in formula for tm in TRANSITION_METALS)
        return has_tm
    
    # Filter by composition
    mask_li_cathode = df["formula"].apply(is_li_cathode)
    
    # Filter by stability (E_hull < 0.5 eV/atom)
    e_hull_col = "e_above_hull"
    if e_hull_col in df.columns:
        mask_stable = df[e_hull_col] < 0.5
    else:
        mask_stable = True
    
    df_filtered = df[mask_li_cathode & mask_stable].copy()
    print(f"  Filtered: {len(df)} -> {len(df_filtered)} Li-cathode materials")
    
    return df_filtered


def download_structures_subset(
    df: pd.DataFrame,
    max_structures: int = 10000,
) -> List[Dict]:
    """
    Download structures for a subset of WBM materials.
    
    Note: Full WBM structures file is ~2GB. We'll download only what we need.
    """
    structures_path = OUTPUT_DIR / "wbm_initial_structures.json.gz"
    
    # If full structures file exists, load from it
    if structures_path.exists():
        print("Loading structures from cached file...")
        import gzip
        with gzip.open(structures_path, "rt") as f:
            all_structures = json.load(f)
        
        # Match to filtered materials
        material_ids = set(df["material_id"].tolist()) if "material_id" in df.columns else set()
        
        structures = []
        for entry in all_structures:
            if entry.get("material_id") in material_ids:
                structures.append(entry)
                if len(structures) >= max_structures:
                    break
        
        return structures
    
    # Otherwise, download only needed structures (if API available)
    print(f"Note: Full structure file not found. Will use metadata only.")
    print(f"  To get structures, download manually from Figshare.")
    
    return []


def save_results(df: pd.DataFrame, structures: List) -> None:
    """Save filtered WBM data."""
    # Rename columns to match our schema
    column_mapping = {
        "material_id": "wbm_id",
        "e_above_hull": "e_hull",
        "formula": "formula",
    }
    
    df_out = df.rename(columns={k: v for k, v in column_mapping.items() if k in df.columns})
    
    # Save metadata
    parquet_path = OUTPUT_DIR / "wbm_li_cathodes.parquet"
    df_out.to_parquet(parquet_path, index=False)
    print(f"Saved {len(df_out)} materials to {parquet_path}")
    
    # Save structures if available
    if structures:
        structures_path = OUTPUT_DIR / "structures.pkl"
        with open(structures_path, "wb") as f:
            pickle.dump(structures, f)
        print(f"Saved {len(structures)} structures to {structures_path}")
    
    # Summary
    summary = {
        "total_materials": len(df_out),
        "structures_available": len(structures),
        "e_hull_range": [float(df_out["e_hull"].min()), float(df_out["e_hull"].max())] if "e_hull" in df_out.columns else None,
        "download_date": time.strftime("%Y-%m-%d"),
        "source": "WBM (Wolverton Battery Materials) via Matbench Discovery",
    }
    
    summary_path = OUTPUT_DIR / "download_summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"Saved summary to {summary_path}")


def main():
    print("=" * 60)
    print("Phase 7D: WBM Li-Cathode Download")
    print("=" * 60)
    
    setup_directories()
    
    # Step 1: Download summary
    print("\n[1/3] Downloading WBM summary...")
    df = download_wbm_summary()
    
    if df is None or len(df) == 0:
        print("Failed to download WBM summary.")
        return
    
    # Step 2: Filter for Li-cathodes
    print("\n[2/3] Filtering Li-cathode materials...")
    df_filtered = filter_li_cathodes(df)
    
    if len(df_filtered) == 0:
        print("No Li-cathode materials found after filtering.")
        return
    
    # Step 3: Get structures (if available)
    print("\n[3/3] Processing structures...")
    structures = download_structures_subset(df_filtered)
    
    # Save results
    save_results(df_filtered, structures)
    
    print("\n" + "=" * 60)
    print("Download complete!")
    print(f"  Li-cathode materials: {len(df_filtered)}")
    print(f"  Structures: {len(structures)}")
    print("=" * 60)


if __name__ == "__main__":
    main()
