#!/usr/bin/env python3
"""Build a provisional screening decision table from ranked QE results."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path


TIER_ORDER = {
    "T0": 0,
    "T1": 1,
    "T2": 2,
    "T3": 3,
    "T4": 4,
    "T5": 5,
}


def to_int(value: str, default: int = 999999) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _split_semicolon_field(value: str) -> list[str]:
    return [part.strip() for part in value.split(";") if part.strip()]


def _tier_rank(tier: str) -> int:
    return TIER_ORDER.get(tier.strip(), -1)


def _load_evidence_index(path: Path) -> dict[str, dict]:
    evidence_by_jarvis: dict[str, dict] = {}
    for row in _read_csv_rows(path):
        jarvis_id = row.get("jarvis_id", "").strip()
        if not jarvis_id:
            continue
        evidence_by_jarvis[jarvis_id] = {
            "evidence_tier": row.get("evidence_tier", "").strip(),
            "evidence_label": row.get("evidence_label", "").strip(),
            "evidence_blockers": _split_semicolon_field(row.get("blockers", "")),
            "evidence_next_step": row.get("recommended_next_step", "").strip(),
        }
    return evidence_by_jarvis


def decide(rank: int, qe_state: str, evidence_tier: str, min_accept_tier: str) -> tuple[str, str, str]:
    evidence_ready = _tier_rank(evidence_tier) >= _tier_rank(min_accept_tier)

    # Primary production gate:
    # - top 20 require both QE completion and evidence threshold to accept
    # - missing evidence blocks promotion even if status snapshots say "done"
    # - lower ranks become backup/unknown
    if rank <= 20:
        if qe_state == "done" and evidence_ready:
            return "accept", "primary", "top20_evidence_ready"
        if qe_state == "done":
            return "hold", "primary", "top20_missing_evidence"
        return "hold", "primary", "top20_unresolved"

    if rank <= 30:
        if qe_state == "done" and evidence_ready:
            return "hold", "backup", "rank21_30_evidence_ready"
        if qe_state == "done":
            return "unknown", "backup", "rank21_30_missing_evidence"
        return "unknown", "backup", "rank21_30_unresolved"

    if qe_state == "done" and evidence_ready:
        return "hold", "longtail", "rank31_50_evidence_ready"
    if qe_state == "done":
        return "unknown", "longtail", "rank31_50_missing_evidence"
    return "unknown", "longtail", "rank31_50_unresolved"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-csv",
        default="reports/dft_batch_jarvis_50_mix_final_ranked_estimated.csv",
        help="Ranked CSV with qe_final_state_est column.",
    )
    parser.add_argument(
        "--out-csv",
        default="reports/screening_decision_provisional.csv",
    )
    parser.add_argument(
        "--out-summary",
        default="reports/screening_decision_summary.txt",
    )
    parser.add_argument(
        "--evidence-csv",
        default="reports/dft_qe_jarvis_50_mix_evidence.csv",
        help="Evidence CSV generated by scripts/50_assign_dft_evidence.py.",
    )
    parser.add_argument(
        "--min-accept-tier",
        default="T1",
        choices=sorted(TIER_ORDER.keys()),
        help="Minimum evidence tier required before a done candidate can be promoted to accept.",
    )
    args = parser.parse_args()

    in_path = Path(args.input_csv)
    out_path = Path(args.out_csv)
    summary_path = Path(args.out_summary)
    evidence_path = Path(args.evidence_csv)

    with in_path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    evidence_by_jarvis = _load_evidence_index(evidence_path)

    rows.sort(key=lambda r: to_int(r.get("rank", "")))

    out_rows = []
    decision_counter: Counter[str] = Counter()
    unresolved_top20 = 0
    missing_evidence_top20 = 0

    for row in rows:
        rank = to_int(row.get("rank", ""))
        qe_state = row.get("qe_final_state_est", "missing")
        evidence = evidence_by_jarvis.get(
            row.get("jarvis_id", "").strip(),
            {
                "evidence_tier": "",
                "evidence_label": "",
                "evidence_blockers": [],
                "evidence_next_step": "",
            },
        )
        evidence_tier = evidence.get("evidence_tier", "")
        decision, priority, reason = decide(rank, qe_state, evidence_tier, args.min_accept_tier)

        if rank <= 20 and decision != "accept":
            unresolved_top20 += 1
            if qe_state == "done" and _tier_rank(evidence_tier) < _tier_rank(args.min_accept_tier):
                missing_evidence_top20 += 1

        decision_counter[decision] += 1

        out_row = {
            "rank": row.get("rank", ""),
            "jarvis_id": row.get("jarvis_id", ""),
            "formula": row.get("formula", ""),
            "p_stable": row.get("p_stable", ""),
            "qe_final_state_est": qe_state,
            "qe_status_source_est": row.get("qe_status_source_est", ""),
            "evidence_tier": evidence_tier,
            "evidence_label": evidence.get("evidence_label", ""),
            "evidence_blockers": ";".join(evidence.get("evidence_blockers", [])),
            "evidence_next_step": evidence.get("evidence_next_step", ""),
            "decision": decision,
            "priority_bucket": priority,
            "decision_reason": reason,
        }
        out_rows.append(out_row)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(out_rows[0].keys()))
        writer.writeheader()
        writer.writerows(out_rows)

    summary_lines = [
        "Screening Decision Summary (Provisional)",
        f"input={in_path}",
        f"output={out_path}",
        f"total_candidates={len(out_rows)}",
        f"accept={decision_counter.get('accept', 0)}",
        f"hold={decision_counter.get('hold', 0)}",
        f"unknown={decision_counter.get('unknown', 0)}",
        f"top20_unresolved={unresolved_top20}",
        f"top20_missing_evidence={missing_evidence_top20}",
        f"min_accept_tier={args.min_accept_tier}",
        "note=Promotion to accept requires both qe_final_state_est=done and evidence tier at or above min_accept_tier. Estimated status alone is insufficient.",
    ]
    summary_path.write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

    print(f"wrote={out_path}")
    print(f"wrote={summary_path}")
    for key in ("accept", "hold", "unknown"):
        print(f"{key}={decision_counter.get(key, 0)}")
    print(f"top20_unresolved={unresolved_top20}")


if __name__ == "__main__":
    main()
